from django.conf import settings

ALIGNMENT_TAGS_CATEGORIES_HIERARCHY_DEFAULT = (
    'STANDARD',
    'GRADE',
    'LEARNING_DOMAIN',
    #'FULL_CODE',
    #'DESCRIPTION'
)

# ALIGNMENT_TAGS_TAG_DEFENITION_CATEGORIES_DEFAULT = ('FULL_CODE', 'DESCRIPTION')

ALIGNMENT_TAGS_CATEGORIES_HIERARCHY = getattr(settings, 'ALIGNMENT_TAGS_CATEGORIES_HIERARCHY', ALIGNMENT_TAGS_CATEGORIES_HIERARCHY_DEFAULT)

# ALIGNMENT_TAGS_TAG_DEFENITION_CATEGORIES = getattr(settings, 'ALIGNMENT_TAGS_TAG_DEFENITION_CATEGORIES', ALIGNMENT_TAGS_TAG_DEFENITION_CATEGORIES_DEFAULT)
#
